#!/usr/bin/env bash
# install.sh — install the Rush DevKit into a target repository.
#
# Usage:
#   ./install.sh <target-repo> [--force] [--dry-run]
#
# Copies `.claude/` (skills, subagents, hooks wiring) and `.rush/` (config schema, templates,
# scripts, hooks, presets, evals) into the target repo. Existing files are never overwritten
# unless --force is given; the kit refuses to clobber a project's own CLAUDE.md, settings.json
# or an already-generated .rush/config.json.
#
# After installing, run `/rush-init` (existing codebase) or `/rush-new` (new product) inside
# the target repo with Claude Code.
set -euo pipefail

KIT_DIR="$(cd "$(dirname "$0")" && pwd)"
FORCE=0
DRY_RUN=0
TARGET=""

usage() {
  sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

while [ $# -gt 0 ]; do
  case "$1" in
    -h|--help) usage 0 ;;
    --force) FORCE=1 ;;
    --dry-run) DRY_RUN=1 ;;
    -*) echo "unknown option: $1" >&2; usage 2 ;;
    *) if [ -n "$TARGET" ]; then echo "unexpected argument: $1" >&2; usage 2; fi; TARGET="$1" ;;
  esac
  shift
done

[ -n "$TARGET" ] || { echo "error: target repository path is required" >&2; usage 2; }
[ -d "$TARGET" ] || { echo "error: '$TARGET' is not a directory" >&2; exit 2; }

TARGET="$(cd "$TARGET" && pwd)"
[ "$TARGET" != "$KIT_DIR" ] || { echo "error: target is the kit itself" >&2; exit 2; }

say()  { printf '%s\n' "$*"; }
step() { printf '  %s\n' "$*"; }

if [ ! -d "$TARGET/.git" ]; then
  say "warning: '$TARGET' is not a git repository."
  say "         The kit relies on git for progress tracking, drift detection and traceability."
fi

copied=0
skipped=0

copy_tree() {
  # copy_tree <relative-source-dir>
  src="$KIT_DIR/$1"
  [ -d "$src" ] || return 0
  # shellcheck disable=SC2044
  for f in $(cd "$src" && find . -type f ! -name '*.pyc' | sed 's|^\./||'); do
    dest="$TARGET/$1/$f"
    if [ -e "$dest" ] && [ "$FORCE" -eq 0 ]; then
      step "skip (exists)  $1/$f"
      skipped=$((skipped + 1))
      continue
    fi
    if [ "$DRY_RUN" -eq 1 ]; then
      step "would copy     $1/$f"
    else
      mkdir -p "$(dirname "$dest")"
      cp "$src/$f" "$dest"
      case "$f" in
        *.sh) chmod +x "$dest" ;;
      esac
      step "copy           $1/$f"
    fi
    copied=$((copied + 1))
  done
}

say "Installing Rush DevKit into: $TARGET"
[ "$DRY_RUN" -eq 1 ] && say "(dry run — nothing will be written)"

copy_tree ".claude"
copy_tree ".rush"

# config.json is generated by /rush-init from config.default.json — never shipped pre-filled,
# because a config that does not match the project is worse than no config at all.
if [ -e "$TARGET/.rush/config.json" ]; then
  step "keep           .rush/config.json (already generated)"
fi

say ""
say "Files copied: $copied   skipped (already present): $skipped"

if [ "$skipped" -gt 0 ] && [ "$FORCE" -eq 0 ]; then
  say ""
  say "Some files already existed and were left untouched. Re-run with --force to overwrite"
  say "them (your CLAUDE.md, .claude/settings.json and .rush/config.json are yours — review any"
  say "overwrite carefully)."
fi

if [ "$DRY_RUN" -eq 0 ]; then
  say ""
  say "Next steps, inside $TARGET with Claude Code:"
  say "  /rush-init              existing codebase — detect, explore, interview, configure"
  say "  /rush-new \"<idea>\"      new product — discovery, stack, scaffold, MVP specs"
  say ""
  say "Then verify with: .rush/scripts/doctor.sh"
fi
